### ISSUE TITLE
the program does not start beyond 39%

### ISSUE THREAD

**Issue by so-left-two-fre** [ShadwLink/Shadow-Mapper#13]
I installed two files for Java, unchecked the option to read files in the root folder of GTA 4 (it still resets) and still the program does not open, freezing at 39%
help me please

**Comment by KilianSteenman** [comment]
Hi! Don’t expect this to program to be useful even if you get past the 39%. 

There are better tools out there to do IV modding.
Anything specific you’re trying to achieve?

**Comment by so-left-two-fre** [comment]
good morning! yes, I would like to save the map of this game in the visual editor

**Comment by KilianSteenman** [comment]
I guess something like https://gtaforums.com/topic/844848-ingame-wpl-tool/ would be your best option.
